package by.epamtc.poliukov.controller;

public enum CommandList {
    LOGIN, REGISTER, LOG_OUT,
    UPLOAD_PHOTO, VIEW_USER, ADD_TENANT, ALL_EMPLOYEES, EMPLOYEES_BY_TYPE,
    GO_TO_EMPLOYEE_BY_TYPE, GO_TO_ADD_TENANT, GO_TO_ADD_WORK_REQUEST, ADD_WORK_REQUEST,
    GO_TO_ADD_SUBQUERY, ADD_SUBQUERY,
    SHOW_ALL_TENANT_REQUESTS, UPDATE_REQUEST_STATUS_TENANT,
    GO_TO_UPDATE_ROLE, UPDATE_ROLE,
    GO_TO_ACTUAL_REQUESTS_EMPLOYEE, ACTUAL_REQUESTS_EMPLOYEE, ACTUAL_REQUESTS_ALL_TYPES,
    GO_TO_SHOW_WORK_PLAN, SHOW_WORK_PLAN,
    GO_TO_ADD_EMPLOYEE, ADD_EMPLOYEE,
    GO_TO_DISPATCHER_WORK_PLAN, DISPATCHER_WORK_PLAN,
    GO_TO_ALL_EMPLOYEE_WORK_PLAN, ALL_EMPLOYEE_WORK_PLAN,
    GO_TO_ADD_REQUEST_TO_WORK_PLAN, ADD_REQUEST_TO_WORK_PLAN,
    DISPATCHER_CLOSE_WORK_REQUEST
}
